---
- name: Perform an E8 oscap scan and upload results to Insights
  hosts: all
  become: true

  tasks:
    - name: Check that host is registered in Insights
      stat:
        path: /etc/insights-client/.registered
      register: result

    - name: Fail if host not registered in Insights
      fail:
        msg: Host not registered in Insights
      when: not result.stat.exists

    - name: Perform oscap scan
      command: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_e8
        --results /tmp/scan_results.xml
        /usr/share/xml/scap/ssg/content/ssg-rhel{{ ansible_distribution_major_version }}-ds.xml
      ignore_errors: yes

    - name: Upload scan results to Insights
      command: >
        insights-client --payload /tmp/scan_results.xml
        --content-type application/vnd.redhat.compliance.something+tgz

    - name: Remove local scan results
      file:
        path: /tmp/scan_results.xml
        state: absent
